import sys
import os
import inspect
from pathlib import Path
from typing import Type, get_type_hints, List, Any
from enum import Enum
from pydantic import BaseModel

# Add backend root to sys.path
backend_root = Path(__file__).parent.parent
sys.path.append(str(backend_root))

# Import models
from common.schemas import ApiCode, Result
from apps.image_processing.schemas import (
    ClassificationRequest,
    ClassificationResponse,
    DenoisingRequest,
    DenoisingResponse,
    SimilarityRequest,
    SimilarityResponse,
)

TYPES_DIR = backend_root.parent / "frontend" / "types"

HEADER = """/**
 * Auto-generated by backend/scripts/generate_types.py
 * Do not edit manually.
 */
"""

def python_type_to_ts(py_type: Any, field_name: str = "") -> str:
    """Map Python types to TypeScript types."""
    # Special handling for 'image' field or generic Any
    if field_name == "image":
        return "Blob | File"
        
    if py_type == str:
        return "string"
    elif py_type == int:
        return "number"
    elif py_type == float:
        return "number"
    elif py_type == bool:
        return "boolean"
    elif hasattr(py_type, "__origin__"):
        # Handle List[T]
        if py_type.__origin__ == list:
            arg = py_type.__args__[0]
            return f"{python_type_to_ts(arg)}[]"
            
    # Fallback to any
    return "any"


def generate_enum(enum_cls: Type[Enum]) -> str:
    """Generate TypeScript Enum."""
    lines = [f"export enum {enum_cls.__name__} {{"]
    for member in enum_cls:
        value = member.value
        if isinstance(value, str):
            value = f"'{value}'"
        lines.append(f"  {member.name} = {value},")
    lines.append("}\n")
    return "\n".join(lines)


def generate_interface(model_cls: Type[BaseModel]) -> str:
    """Generate TypeScript Interface from Pydantic Model."""
    lines = [f"export interface {model_cls.__name__} {{"]
    
    type_hints = get_type_hints(model_cls)
    
    for name, py_type in type_hints.items():
        ts_type = python_type_to_ts(py_type, field_name=name)
        lines.append(f"  {name}: {ts_type};")

    lines.append("}\n")
    return "\n".join(lines)


def generate_result_interface() -> str:
    """Manually generate the Result interface."""
    return """
export interface Result<T = any> {
  code: ApiCode | number;
  data: T;
  message: string;
}
"""

def main():
    print(f"Generating types to directory {TYPES_DIR}...")
    
    # ensure directory exists
    TYPES_DIR.mkdir(parents=True, exist_ok=True)
    
    # 1. Generate common.ts
    common_content = [HEADER]
    common_content.append(generate_enum(ApiCode))
    common_content.append(generate_result_interface())
    
    with open(TYPES_DIR / "common.ts", "w", encoding="utf-8") as f:
        f.write("\n".join(common_content))
    print(f"Generated common.ts")

    # 2. Generate image-processing.ts
    ip_content = [HEADER]
    ip_models = [
        ClassificationRequest,
        ClassificationResponse,
        DenoisingRequest,
        DenoisingResponse,
        SimilarityRequest,
        SimilarityResponse,
    ]
    for model in ip_models:
        ip_content.append(generate_interface(model))
        
    with open(TYPES_DIR / "image-processing.ts", "w", encoding="utf-8") as f:
        f.write("\n".join(ip_content))
    print(f"Generated image-processing.ts")

    # 3. Generate api.ts (index)
    index_content = [HEADER]
    index_content.append("export * from './common';")
    index_content.append("export * from './image-processing';")
    
    with open(TYPES_DIR / "api.ts", "w", encoding="utf-8") as f:
        f.write("\n".join(index_content))
    print(f"Generated api.ts")
        
    print("Done!")


if __name__ == "__main__":
    main()
