/**
 * Auto-generated by backend/scripts/generate_types.py
 * Do not edit manually.
 */

export enum ApiCode {
  SUCCESS = 200,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  VALIDATION_ERROR = 1001,
  BUSINESS_ERROR = 2000,
  SERVER_ERROR = 500,
}


export interface Result<T = any> {
  code: ApiCode | number;
  data: T;
  message: string;
  traceId?: string;
}
