/**
 * Auto-generated by backend/scripts/generate_types.py
 * Do not edit manually.
 */

export interface ClassificationRequest {
  image: Blob | File;
}

export interface ClassificationResponse {
  result: string;
}

export interface DenoisingRequest {
  image: Blob | File;
}

export interface DenoisingResponse {
  noisy_img: string;
  denoised_image: string;
}

export interface SimilarityRequest {
  image: Blob | File;
  num_images: number;
}

export interface SimilarityResponse {
  image_urls: string[];
}
